name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['9.0.x']

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Find solution file
      id: find-sln
      run: |
        SLN_FILE=$(find . -name "*.sln" | head -1)
        if [ -z "$SLN_FILE" ]; then
          CSPROJ_FILE=$(find . -name "*.csproj" | head -1)
          echo "project_file=$CSPROJ_FILE" >> $GITHUB_OUTPUT
        else
          echo "project_file=$SLN_FILE" >> $GITHUB_OUTPUT
        fi

    - name: Restore dependencies
      run: dotnet restore "${{ steps.find-sln.outputs.project_file }}"

    - name: Build
      run: dotnet build "${{ steps.find-sln.outputs.project_file }}" --no-restore --configuration Release

    - name: Test
      run: dotnet test "${{ steps.find-sln.outputs.project_file }}" --no-build --configuration Release --verbosity normal

    - name: Publish
      run: dotnet publish "${{ steps.find-sln.outputs.project_file }}" --no-build --configuration Release --output ./publish

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: ./publish/

  code-quality:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Find solution file
      id: find-sln
      run: |
        SLN_FILE=$(find . -name "*.sln" | head -1)
        if [ -z "$SLN_FILE" ]; then
          CSPROJ_FILE=$(find . -name "*.csproj" | head -1)
          echo "project_file=$CSPROJ_FILE" >> $GITHUB_OUTPUT
        else
          echo "project_file=$SLN_FILE" >> $GITHUB_OUTPUT
        fi

    - name: Restore dependencies
      run: dotnet restore "${{ steps.find-sln.outputs.project_file }}"

    - name: Run code analysis
      run: dotnet build "${{ steps.find-sln.outputs.project_file }}" --configuration Release --verbosity normal
